{
  "statusCode": 500,
  "body": "{\"error\": \"Parameter validation failed:\\nUnknown parameter in input: \\\"knowledgeBaseConfiguration\\\", must be one of: agentAliasId, agentId, bedrockModelConfigurations, enableTrace, endSession, inputText, memoryId, sessionId, sessionState, sourceArn, streamingConfigurations\", \"stackTrace\": \"Traceback (most recent call last):\\n  File \\\"/var/task/lambda_function.py\\\", line 41, in lambda_handler\\n    response = bedrock_agent.invoke_agent(\\n        agentId='HPJTUOMEEN',\\n    ...<3 lines>...\\n        inputText=user_input\\n    )\\n  File \\\"/var/lang/lib/python3.13/site-packages/botocore/client.py\\\", line 569, in _api_call\\n    return self._make_api_call(operation_name, kwargs)\\n           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^\\n  File \\\"/var/lang/lib/python3.13/site-packages/botocore/client.py\\\", line 980, in _make_api_call\\n    request_dict = self._convert_to_request_dict(\\n        api_params=api_params,\\n    ...<3 lines>...\\n        headers=additional_headers,\\n    )\\n  File \\\"/var/lang/lib/python3.13/site-packages/botocore/client.py\\\", line 1047, in _convert_to_request_dict\\n    request_dict = self._serializer.serialize_to_request(\\n        api_params, operation_model\\n    )\\n  File \\\"/var/lang/lib/python3.13/site-packages/botocore/validate.py\\\", line 381, in serialize_to_request\\n    raise ParamValidationError(report=report.generate_report())\\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\\nUnknown parameter in input: \\\"knowledgeBaseConfiguration\\\", must be one of: agentAliasId, agentId, bedrockModelConfigurations, enableTrace, endSession, inputText, memoryId, sessionId, sessionState, sourceArn, streamingConfigurations\\n\"}"
